### ISSUE TITLE
remove the necessity of yarn test:forge

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/morpho-blue-irm#124]

**Comment by MathisGD** [comment]
https://github.com/morpho-org/morpho-blue-irm/pull/123#discussion_r1494463893

**Comment by MathisGD** [comment]
https://github.com/morpho-org/morpho-blue-irm/pull/123#discussion_r1486494169

**Comment by Rubilmax** [comment]
I knew we would skip this, hence why i didn't want to merge it in the first place ^^
