### ISSUE TITLE
Update equality comment

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-blue-irm#79]
We may want to clarify that the following equality is not correct when `endRateAtTarget` has been bounded.

https://github.com/morpho-labs/morpho-blue-irm/blob/77ed9c17917bba7a7175702cb23f33e1ba5697cd/src/SpeedJumpIrm.sol#L144-L145

For reference: #73

**Comment by MathisGD** [comment]
fixed by #82
