### ISSUE TITLE
add test for underestimation

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/morpho-blue-irm#97]
https://github.com/morpho-org/morpho-blue-irm/blob/c2b1732fc332d20a001ca505aea76bd475e95ef1/src/AdaptiveCurveIrm.sol#L135-L136

quantify and test this underestimation

**Comment by Rubilmax** [comment]
Some tests were added in #80 and some other comparison tests were written by @adhusson on the [`test/rates-test-2`](https://github.com/morpho-org/morpho-blue-irm/tree/test/rates-test-2) branch

**Comment by MathisGD** [comment]
indeed

for some reasons i missed this PR
